from typing import Protocol
from .conflict import ConflictContext
from .server_idempotency import IdempotencyRecord


class SyncStatePersistence(Protocol):
    def lock_idempotency(self, tenant_id: str, project_id: str, key: str) -> None: ...
    def get_idempotency(self, tenant_id: str, project_id: str, key: str) -> IdempotencyRecord | None: ...
    def put_idempotency(self, record: IdempotencyRecord) -> None: ...
    def save_conflict(self, mutation_id: str, tenant_id: str, project_id: str, context: ConflictContext) -> None: ...
    def get_conflict(self, mutation_id: str, tenant_id: str, project_id: str) -> ConflictContext | None: ...
