name: Runner Diagnostic

on:
  push:
    paths:
      - ".github/workflows/runner-diagnostic.yml"
  workflow_dispatch:

jobs:
  runner:
    runs-on: windows-latest
    steps:
      - name: Runner start
        shell: pwsh
        run: |
          Write-Output "runner-started"
          $PSVersionTable.PSVersion
          Get-ComputerInfo | Select-Object WindowsProductName
